### ISSUE TITLE
Paste/Copy via web

### ISSUE THREAD

**Issue by adrum** [tesla-android/flutter-app#9]
Tangential to #8, when I was setting up my accounts from desktop browser, I had to manually key in my generated passwords 🫠

I thought it might be nice to capture the at least paste event and send it over the web socket to trigger an Android paste. Copy would be nice too, but I'm not quite sure that's necessary.

**Comment by mikegapinski** [comment]
This is not going to happen, I don't have a virtual keyboard attached to anything that has contact with the frontend. I might do the integration with the Tesla keyboard at some point(instead of showing an Android keyboard on the screen the one from Tesla OS would show up). But that is something very low key, I have bigger fish to fry now ;)
